# changed storageClassName
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: caddy-data
  name: caddy-data
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
