apiVersion: v1
data:
  Caddyfile: |-
    m210.localhost {

        log {
            format console
            level error
        }

        handle /api* {
            reverse_proxy backend:8080
        }

        handle {
            reverse_proxy frontend:80
        }

    }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: caddy-proxy
  name: caddy-proxy-cm0
